/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UofgFooter {
    }
    interface UofgHeader {
        /**
          * The title of the pages that the header is being used on. For example, for the Convocation pages, this would be set to "Convocation".
         */
        "pageTitle": string;
        /**
          * The URL to the home/landing page for the pages the header is being used on. For example, for the Convocation pages, this would be set to "https://www.uoguelph.ca/convocation/".
         */
        "pageUrl": string;
    }
    interface UofgMenu {
        /**
          * Controls whether the menu should automatically collapse when the focused element in the page is not contained within the menu (e.g. it's button or content). This is useful for when you want the menu to collapse whenever a user interacts with any other part of the page.
         */
        "autoCollapse": boolean;
        /**
          * Collapse the menu. This is the same as setting the expanded state to false.
          * @returns empty Promise.
         */
        "collapse": () => Promise<void>;
        /**
          * Expand the menu. This is the same as setting the expanded state to true.
          * @returns empty Promise.
         */
        "expand": () => Promise<void>;
        /**
          * Get the current expanded state of the menu.
          * @returns A promise which will resolve to the current expanded state.
         */
        "getExpanded": () => Promise<boolean>;
        /**
          * Set the expanded state of the menu.
          * @param value The new expanded state.
         */
        "setExpanded": (value: boolean) => Promise<void>;
        /**
          * Toggle the expanded state of the menu.
          * @returns A promise which will resolve to the new expanded state.
         */
        "toggle": () => Promise<boolean>;
    }
}
export interface UofgMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUofgMenuElement;
}
declare global {
    interface HTMLUofgFooterElement extends Components.UofgFooter, HTMLStencilElement {
    }
    var HTMLUofgFooterElement: {
        prototype: HTMLUofgFooterElement;
        new (): HTMLUofgFooterElement;
    };
    interface HTMLUofgHeaderElement extends Components.UofgHeader, HTMLStencilElement {
    }
    var HTMLUofgHeaderElement: {
        prototype: HTMLUofgHeaderElement;
        new (): HTMLUofgHeaderElement;
    };
    interface HTMLUofgMenuElement extends Components.UofgMenu, HTMLStencilElement {
    }
    var HTMLUofgMenuElement: {
        prototype: HTMLUofgMenuElement;
        new (): HTMLUofgMenuElement;
    };
    interface HTMLElementTagNameMap {
        "uofg-footer": HTMLUofgFooterElement;
        "uofg-header": HTMLUofgHeaderElement;
        "uofg-menu": HTMLUofgMenuElement;
    }
}
declare namespace LocalJSX {
    interface UofgFooter {
    }
    interface UofgHeader {
        /**
          * The title of the pages that the header is being used on. For example, for the Convocation pages, this would be set to "Convocation".
         */
        "pageTitle"?: string;
        /**
          * The URL to the home/landing page for the pages the header is being used on. For example, for the Convocation pages, this would be set to "https://www.uoguelph.ca/convocation/".
         */
        "pageUrl"?: string;
    }
    interface UofgMenu {
        /**
          * Controls whether the menu should automatically collapse when the focused element in the page is not contained within the menu (e.g. it's button or content). This is useful for when you want the menu to collapse whenever a user interacts with any other part of the page.
         */
        "autoCollapse"?: boolean;
        /**
          * Dispatched whenever the menu is expanding or collapsing and the animation has ended. This event is not dispatched if the animation is disabled (e.g. due to reduced motion, css variable set to none, or lack of Web Animations API support).
         */
        "onAnimationEnded"?: (event: UofgMenuCustomEvent<boolean>) => void;
        /**
          * Dispatched whenever the menu is expanding or collapsing and the animation has started. This event is not dispatched if the animation is disabled (e.g. due to reduced motion, css variable set to none, or lack of Web Animations API support).
         */
        "onAnimationStarted"?: (event: UofgMenuCustomEvent<boolean>) => void;
        /**
          * Dispatched whenever the menu is collapsed whether by user interaction or programmatically (e.g. collapse()).
         */
        "onCollapsed"?: (event: UofgMenuCustomEvent<void>) => void;
        /**
          * Dispatched whenever the menu is expanded whether by user interaction or or programmatically (e.g. expand()).
         */
        "onExpanded"?: (event: UofgMenuCustomEvent<void>) => void;
    }
    interface IntrinsicElements {
        "uofg-footer": UofgFooter;
        "uofg-header": UofgHeader;
        "uofg-menu": UofgMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uofg-footer": LocalJSX.UofgFooter & JSXBase.HTMLAttributes<HTMLUofgFooterElement>;
            "uofg-header": LocalJSX.UofgHeader & JSXBase.HTMLAttributes<HTMLUofgHeaderElement>;
            "uofg-menu": LocalJSX.UofgMenu & JSXBase.HTMLAttributes<HTMLUofgMenuElement>;
        }
    }
}
